# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: NA_YUN_HO
title: README
email: ring147@naver.com
# email_title: Email (Email title override)
phone: 010-8586-4484
# phone_title: Phone (Phone title override)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  nayunho
facebook_username: profile.php?id=100007833941839
instagram_username: naa_yunhoo
youtube_username: nayunho

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/README.jpg
about_content: | # this will include new lines to allow paragraphs
    - 생년월일: 1999-09-28
    - 현주소: 경기도 천마산로 65-2
    - 취미/특기:  
    취미=> 영화 보기 및 음악 듣기  
    특기=> 상황 판단
    - 대학교: [한림대학교]("https://www.hallym.ac.kr/")
    - 소속: 정보 과학 대학
    - 전공: 스마트 IOT
    - 학력사항:  
    2014~2016=>판곡중학교  => 졸업  
    2016~2018=>호평고등학교=> 졸업  
    2018~    =>한림대학교  => 재학
    - 취득 자격증:  
    자격증: 정보 처리 기능사  
    발급기간: Q-net
    
content:
  - title: programming language skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      java  
      C  
      python
  - title: MBTI
    layout: text
    content: | # this will include new lines to allow paragraphs
      ISTJ  
      주어진 업무나 책임을 끝까지 완료하고, 예고없이 갑작스러운 변화를 싫어합니다.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
